dist: xenial
os: linux
language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
    - composer self-update

install:
    - composer install -o --prefer-source --no-interaction

script:
    - php vendor/bin/simple-phpunit -v
