name: Tag auto

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 1 * *"

jobs:
  tag:
    name: "Automatic tag creation"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.4"
          coverage: "none"
          tools: composer:v2
          ini-values: "date.timezone=Europe/Paris"
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v2"

      - name: "Configure upstream"
        run: "git remote add upstream https://github.com/fivefilters/ftr-site-config.git"

      - name: "Setup git config"
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: "Create tag"
        run: "make update"
